### PR TITLE
Fix broken href on title

### PR DESCRIPTION
**Pull request by gb-beng**

### CODE REVIEW

**Review by wmelder — COMMENTED** [review]
This wass indeed not the correct href and you made the right correction. Thanks for noticing and fixing.

**Comment by wmelder** [comment]
@gb-beng Where did you find this href? I mean if I look at the UI I don't see any 'branding'.

**Comment by gb-beng** [comment]
It's assigned to the page title 'Query the Sound and Vision media catalog as Open Data'.

**Comment by wmelder** [comment]
@gb-beng o wow, that's so big and prominent that I overlooked it... Please merge... it will trigger the automatic vercel deployment...

**Comment by wmelder** [comment]
nb you can see some 'before-prod-deploy' deployments already when cllicking on 'preview' (that is shown when you click 'show environments')

**Comment by gb-beng** [comment]
> nb you can see some 'before-prod-deploy' deployments already when cllicking on 'preview' (that is shown when you click 'show environments')

Yup, spotted it! That's a neat feature, a per-branch preview url.

**Pull request merged**
